services:
  - type: web
    name: lms-carder
    runtime: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: APP_NAME
        value: LMS CARDER
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_LOCALE
        value: es
      - key: APP_TIMEZONE
        value: America/Bogota
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local